# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 飲冰
email: facai.yan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  富貴福澤，將厚吾之生也；貧賤憂戚，庸玉女於成也。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://facaiy.com" # the base hostname & protocol for your site
github_username:  facaiy

# Build settings
markdown: kramdown
